const $=id=>document.getElementById(id);const today=()=>new Date().toISOString().slice(0,10);const key='tc_v3_data';
const starter={settings:{tHU:15,tUS:15},drivers:['MK','CY'],days:{}};
const sample=()=>[{id:uid(),p:'E',from:'Home',to:'Unit Base',time:'06:55',driver:'MK'},{id:uid(),p:'JOS',from:'Home',to:'Unit Base',time:'08:10',driver:'MK'},{id:uid(),p:'M',from:'Home',to:'Unit Base',time:'08:45',driver:'MK'},{id:uid(),p:'M & JOS',from:'Unit Base',to:'SET',time:'09:35',driver:'MK'},{id:uid(),p:'ROS',from:'Home',to:'Unit Base',time:'07:20',driver:'CY'},{id:uid(),p:'JB',from:'Home',to:'Unit Base',time:'07:50',driver:'CY'},{id:uid(),p:'E',from:'Unit Base',to:'SET',time:'08:15',driver:'CY'},{id:uid(),p:'JB & ROS',from:'Unit Base',to:'SET',time:'08:50',driver:'CY'}];
let data=JSON.parse(localStorage.getItem(key)||'null')||starter;let current=today();if(!data.days[current])data.days[current]=sample();
function uid(){return Math.random().toString(36).slice(2,10)}function save(){localStorage.setItem(key,JSON.stringify(data))}function mins(t){let[a,b]=t.split(':').map(Number);return a*60+b}function clock(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}function dur(j){return j.from==='Home'&&j.to==='Unit Base'?+data.settings.tHU:j.from==='Unit Base'&&j.to==='SET'?+data.settings.tUS:15}function end(j){return mins(j.time)+dur(j)}function overlaps(a,b){return mins(a.time)<end(b)&&mins(b.time)<end(a)}function journeys(){return data.days[current]||(data.days[current]=[])}
function conflicts(){let out=[];for(const d of data.drivers){let js=journeys().filter(j=>j.driver===d);for(let i=0;i<js.length;i++)for(let k=i+1;k<js.length;k++)if(overlaps(js[i],js[k]))out.push([js[i],js[k],d]);}return out}function free(d,j,ignore){return !journeys().some(x=>x.driver===d&&x.id!==ignore&&overlaps(x,j))}
function render(focus=null){$('datePick').value=current;let cs=conflicts(),bad=new Set();cs.forEach(([a,b])=>{bad.add(a.id);bad.add(b.id)});$('drivers').innerHTML='';for(const d of data.drivers){let card=document.createElement('div');card.className='driver';let has=journeys().some(j=>j.driver===d&&bad.has(j.id));card.innerHTML=`<div class="driverHead"><h2>🚗 ${d}</h2><span class="status ${has?'bad':''}">${has?'Conflict 🔴':'Available ✅'}</span></div>`;journeys().filter(j=>j.driver===d).sort((a,b)=>mins(a.time)-mins(b.time)).forEach(j=>{let btn=document.createElement('button');btn.id='trip-'+j.id;btn.className='journey '+(bad.has(j.id)?'conflict ':'')+(j.id===focus?'newConflict':'');btn.innerHTML=`<div class="time">${j.time}</div><div><div class="route">${j.from} → ${j.to}</div><div class="arrive">Arrive ${clock(end(j))}</div></div><div class="bubble">${j.p}</div>`;btn.onclick=()=>openJourney(j);card.appendChild(btn)});$('drivers').appendChild(card)}showWarning(cs,focus);save()}
function showWarning(cs,focus){let w=$('warning');if(!cs.length){w.classList.add('hidden');w.innerHTML='';return}w.classList.remove('hidden');let[a,b,d]=cs[0],newer=focus&&(a.id===focus||b.id===focus)?journeys().find(j=>j.id===focus):b,old=newer.id===a.id?b:a;let fixes=data.drivers.filter(x=>x!==newer.driver&&free(x,newer,newer.id));w.innerHTML=`🔴 <b>Conflict</b><br>${newer.driver} is already booked.<br><br><b>${old.p}</b> ${old.from} → ${old.to}, ${old.time}–${clock(end(old))}<br><b>${newer.p}</b> ${newer.from} → ${newer.to}, ${newer.time}–${clock(end(newer))}<br><br>${fixes.length?fixes.map(f=>`<button onclick="moveTrip('${newer.id}','${f}')">Move ${newer.p} to ${f}</button>`).join(' '):'No driver free at this time.'}`;setTimeout(()=>document.getElementById('trip-'+old.id)?.scrollIntoView({behavior:'smooth',block:'center'}),100)}
function moveTrip(id,d){let j=journeys().find(x=>x.id===id);if(j)j.driver=d;render(id)}window.moveTrip=moveTrip;
function fillDrivers(sel,val){sel.innerHTML=data.drivers.map(d=>`<option ${d===val?'selected':''}>${d}</option>`).join('')}function openJourney(j={}){$('journeyId').value=j.id||'';$('passenger').value=j.p||'';$('from').value=j.from||'Home';$('to').value=j.to||'Unit Base';$('time').value=j.time||'09:00';fillDrivers($('driver'),j.driver||data.drivers[0]);$('deleteJourney').style.display=j.id?'block':'none';$('journeyDialog').showModal()}
$('journeyForm').onsubmit=e=>{e.preventDefault();let id=$('journeyId').value||uid();let j={id,p:$('passenger').value,from:$('from').value,to:$('to').value,time:$('time').value,driver:$('driver').value};let arr=journeys(),i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=j;else arr.push(j);$('journeyDialog').close();render(id)};$('deleteJourney').onclick=()=>{data.days[current]=journeys().filter(j=>j.id!==$('journeyId').value);$('journeyDialog').close();render()};$('addJourney').onclick=()=>openJourney();
$('datePick').onchange=e=>{current=e.target.value;if(!data.days[current])data.days[current]=[];render()};$('todayBtn').onclick=()=>{current=today();if(!data.days[current])data.days[current]=sample();render()};$('copyToday').onclick=()=>{let t=today();data.days[current]=(data.days[t]||sample()).map(j=>({...j,id:uid()}));render()};$('clearDay').onclick=()=>{if(confirm('Clear this day?')){data.days[current]=[];render()}};
$('settingsBtn').onclick=()=>{ $('tHU').value=data.settings.tHU;$('tUS').value=data.settings.tUS;drawDriverSettings();$('settingsDialog').showModal()};function drawDriverSettings(){let box=$('driverSettings');box.innerHTML='';data.drivers.forEach((d,i)=>{let r=document.createElement('div');r.className='driverRow';r.innerHTML=`<input value="${d}" data-i="${i}"><button type="button" ${data.drivers.length<2?'disabled':''} onclick="removeDriver(${i})">Remove</button>`;box.appendChild(r)})}function removeDriver(i){let old=data.drivers[i];if(!confirm('Remove '+old+'?'))return;data.drivers.splice(i,1);for(const day of Object.values(data.days))day.forEach(j=>{if(j.driver===old)j.driver=data.drivers[0]});drawDriverSettings()}window.removeDriver=removeDriver;$('addDriver').onclick=()=>{if(data.drivers.length>=5)return alert('Maximum 5 drivers');data.drivers.push('Driver '+data.drivers.length);drawDriverSettings()};$('settingsForm').onsubmit=e=>{e.preventDefault();let old=[...data.drivers];data.settings.tHU=+$('tHU').value||15;data.settings.tUS=+$('tUS').value||15;data.drivers=[...document.querySelectorAll('#driverSettings input')].map(x=>x.value.trim()).filter(Boolean).slice(0,5);old.forEach((name,i)=>{let nn=data.drivers[i];if(nn&&nn!==name)for(const day of Object.values(data.days))day.forEach(j=>{if(j.driver===name)j.driver=nn})});$('settingsDialog').close();render()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
